server:
  error:
    include-stacktrace: always
spring:
  data:
    mongodb:
      database: books
      host: ousmongotrial
      port: 27017
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
stripe:
  secretKey: sk_test_51NnN9MHGh6aJWlEaIwTr8km52wbq8iZPqrzOWtzv6cmJF5in4jvJ8hCdwmCVBBfugY1m58WOvbx1Y5EHS2pmObqe00qYsbkPpq