on:
  push:
    branches:
      - main
jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Commit changes
        run: |
          git config --global user.email "sangaryousmane@gmail.com"
          git config --global user.name "sangaryousmane"
          git add .
          git commit -m "Automatic code pushes by actions"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.BOOK_STORE_SECRET }}

